name: Pull request
on: pull_request

jobs:
  commitsar:
    runs-on: ubuntu-latest
    name: Verify commit messages
    steps:
      - uses: actions/checkout@v1
      - name: Run commitsar
        uses: docker://aevea/commitsar@sha256:842a1896b91479565a2db711ecacd8cf3744af56590345e27cf5197438eddef8
